{{- $appName := .Values.appName -}}
{{- $annotations := .Values.keycloak.annotations -}}
{{- $labels := .Values.keycloak.labels -}}
{{- $additionalOptions := .Values.keycloak.additionalOptions -}}
{{- $resources := .Values.keycloak.resources -}}
{{- $image := .Values.keycloak.image -}}
{{- $db := .Values.db -}}
{{- $hostname := .Values.keycloak.hostname -}}
{{- $http := .Values.keycloak.http -}}
{{- $ingress := .Values.keycloak.ingress -}}
{{- $unsupported := .Values.keycloak.unsupported -}}
{{- $cache := .Values.keycloak.cache -}}
{{- $startOptimized := .Values.keycloak.startOptimized -}}
{{- $features := .Values.keycloak.features -}}
{{- $transaction := .Values.keycloak.transaction -}}
{{- $truststores := .Values.keycloak.truststores -}}

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ $appName }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- if $labels }}
    {{- toYaml $labels | nindent 4 }}
  {{- end }}
spec:
  startOptimized: false
  {{- if $cache }}
  cache:
     {{- toYaml $cache | nindent 4 }}
  {{- end }}
  {{- if $unsupported }}
  unsupported:
     {{- toYaml $unsupported | nindent 4 }}
  {{- end }}
  {{- if $image }}
  image: {{ $image }}
  {{- end }}
  {{- if $additionalOptions }}
  additionalOptions:
    {{- toYaml $additionalOptions | nindent 4 }}
  {{- end }}
  {{- if $db }}
  db:
    {{- toYaml $db | nindent 4 }}
  {{- end }}
  {{- if $hostname }}
  hostname:
    {{- toYaml $hostname | nindent 4 }}
  {{- end }}
  {{- if $http }}
  http:
    {{- toYaml $http | nindent 4 }}
  {{- end }}
  {{- if $ingress }}
  ingress:
    {{- toYaml $ingress | nindent 4 }}
  {{- end }}
  instances: {{ .Values.keycloak.replicas }}
  proxy:
    headers: {{ .Values.proxy.headers }}
  {{- if $resources }}
  resources:
    {{- toYaml $resources | nindent 4 }}
  {{- end }} 
  {{- if $features }}
  features:
    {{- toYaml $features | nindent 4 }}
  {{- end }} 
  {{- if $transaction }}
  transaction:
    {{- toYaml $transaction | nindent 4 }}
  {{- end }} 
  {{- if $truststores }}
  truststores:
    {{- toYaml $truststores | nindent 4 }}
  {{- end }} 
