{{- $appName := .Values.appName -}}
{{- $annotations := .Values.kcdeployment.annotations -}}
{{- $labels := .Values.kcdeployment.labels -}}
{{- $additionalOptions := .Values.kcdeployment.additionalOptions -}}
{{- $resources := .Values.kcdeployment.resources -}}
{{- $image := .Values.kcdeployment.image -}}
{{- $db := .Values.db -}}
{{- $hostname := .Values.kcdeployment.hostname -}}
{{- $http := .Values.kcdeployment.http -}}
{{- $ingress := .Values.kcdeployment.ingress -}}
{{- $unsupported := .Values.kcdeployment.unsupported -}}
{{- $cache := .Values.kcdeployment.cache -}}
{{- $startOptimized := .Values.kcdeployment.startOptimized -}}

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ $appName }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- if $labels }}
    {{- toYaml $labels | nindent 4 }}
  {{- end }}
spec:
  startOptimized: false
  {{- if $cache }}
  cache:
     {{- toYaml $cache | nindent 4 }}
  {{- end }}
  {{- if $unsupported }}
  unsupported:
     {{- toYaml $unsupported | nindent 4 }}
  {{- end }}
  {{- if $image }}
  image: {{ $image }}
  {{- end }}
  {{- if $additionalOptions }}
  additionalOptions:
    {{- toYaml $additionalOptions | nindent 4 }}
  {{- end }}
  {{- if $db }}
  db:
    {{- toYaml $db | nindent 4 }}
  {{- end }}
  {{- if $hostname }}
  hostname:
    {{- toYaml $hostname | nindent 4 }}
  {{- end }}
  {{- if $http }}
  http:
    {{- toYaml $http | nindent 4 }}
  {{- end }}
  {{- if $ingress }}
  ingress:
    {{- toYaml $ingress | nindent 4 }}
  {{- end }}
  instances: {{ .Values.kcdeployment.replicas }}
  proxy:
    headers: {{ .Values.proxy.headers }}
  {{- if $resources }}
  resources:
    {{- toYaml $resources | nindent 4 }}
  {{- end }}  

{{- if .Values.deployment }}
## StatefulSet RHBK gerado pelo operator
{{- $stannotations := .Values.deployment.annotations -}}
{{- $stlabels := .Values.deployment.labels -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appName }}
  {{- if $stannotations }}
  annotations:
    {{- toYaml $stannotations | nindent 4 }}
  {{- end }}
  {{- if $stlabels }}
  labels:
    {{- toYaml $stlabels | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- if $stlabels }}
    matchLabels:
      {{- toYaml $stlabels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- if $stlabels }}
      labels:
        {{- toYaml $stlabels | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: keycloak
          image: {{ $image }}
          env:
          - name: NODE_NAME2
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          envFrom:
          - configMapRef:
              name: {{ .Values.deployment.configMapEnv }}
{{- end }}