{{- if .Values.keyValueSecret }}

{{- $annotations := .Values.keyValueSecret.annotations -}}
{{- $labels := .Values.keyValueSecret.labels -}}
{{- $appName := .Values.appName -}}
{{- $keyValueSecret := .Values.keyValueSecret -}}
{{- range $keyValueSecretInstance := .Values.keyValueSecret.instance }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $keyValueSecretInstance.name }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ $appName }}
    app.kubernetes.io/component: {{ $appName }}
    app.kubernetes.io/instance: {{ $appName }}
    app.kubernetes.io/name: {{ $appName }}
  {{- if $labels }}
    {{- toYaml $labels | nindent 4 }}
  {{- end }}
{{- if $keyValueSecretInstance.data }}
data:
  {{- toYaml $keyValueSecretInstance.data | nindent 2 }}
{{- end }}
{{- if $keyValueSecretInstance.stringData }}
stringData:
  {{- toYaml $keyValueSecretInstance.stringData | nindent 2 }}
{{- end }}
{{- if $keyValueSecretInstance.type }}
type: {{ $keyValueSecretInstance.type }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.filesValueSecret }}

{{- $appName := .Values.appName -}}
{{- $annotations2 := .Values.filesValueSecret.annotations -}}
{{- $labels2 := .Values.filesValueSecret.labels -}}
{{- $filesValueSecret := .Values.filesValueSecret -}}
{{- range $filesValueSecretInstance := .Values.filesValueSecret.instance }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $filesValueSecretInstance.name }}
  {{- if $annotations2 }}
  annotations:
    {{- toYaml $annotations2 | nindent 4 }}
  {{- end }}
  labels:
    app: {{ $appName }}
    app.kubernetes.io/component: {{ $appName }}
    app.kubernetes.io/instance: {{ $appName }}
    app.kubernetes.io/name: {{ $appName }}
  {{- if $labels2 }}
    {{- toYaml $labels2 | nindent 4 }}
  {{- end }}
{{- if $filesValueSecretInstance.data }}
data:
  {{- toYaml $filesValueSecretInstance.data | nindent 2 }}
{{- end }}
{{- if $filesValueSecretInstance.stringData }}
stringData:
  {{- toYaml $filesValueSecretInstance.stringData | nindent 2 }}
{{- end }}
{{- if $filesValueSecretInstance.type }}
type: {{ $filesValueSecretInstance.type }}
{{- end }}
{{- end }}
{{- end }}