{{- if .Values.service }}
{{- $appName := .Values.appName -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
spec:
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  type: {{ .Values.service.type }}
  ports:
    {{- range $ports := .Values.ports }}
    - name: {{ $ports.name }}
      protocol: {{ $ports.protocol }}
      port: {{ $ports.port }}
      targetPort: {{ $ports.port }}
    {{- end }}
{{- end }}


