{{- if .Values.deployment }}
{{- $appName := .Values.appName -}}
## Representação StatefulSet RHBK gerado pelo operator
{{- $stannotations := .Values.deployment.annotations -}}
{{- $stlabels := .Values.deployment.labels -}}
{{- $stimage := .Values.keycloak.image -}}
{{- $stenv := .Values.deployment.env -}}
{{- $stenvFrom := .Values.deployment.envFrom -}}
{{- $stcontainerName := .Values.deployment.containerName -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appName }}
  {{- if $stannotations }}
  annotations:
    {{- toYaml $stannotations | nindent 4 }}
  {{- end }}
  {{- if $stlabels }}
  labels:
    {{- toYaml $stlabels | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- if $stlabels }}
    matchLabels:
      {{- toYaml $stlabels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- if $stlabels }}
      labels:
        {{- toYaml $stlabels | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ $stcontainerName }}
          # image: {{ $stimage }}
          {{- if $stenv }}
          env:
            {{- toYaml $stenv | nindent 12 }}
          {{- end }}
          {{- if $stenvFrom }}
          envFrom:
            {{- toYaml $stenvFrom | nindent 12 }}
          {{- end }}    
{{- end }}